source("global.R")




ui = dashboardPage(

    header = dashboardHeader(title = "iMessage Browser - 0.3",
       
        titleWidth = 350
       
    ),
#------------------Sidebar    
    sidebar = dashboardSidebar(
        width = 350,
        minified = FALSE,
        
        fileInput("file","Select backup file", placeholder = "No file selected"),
        fileInput("abfile","Select Address Book file", placeholder = "No file selected"),
        hr(),
        selectInput("contact", 'Select Contact', choices = NULL)
       
       
    ),
#-----------------Body    
body = dashboardBody(
      
      
      
      
  tabBox(width=12,
          id = "tabsetView",
          tabPanel("Chat View", 
                   fluidRow(  
                     box(title = "Chat view",id='messageBox', collapsible = TRUE, collapsed = TRUE,  solidHeader = FALSE,  status = "warning", 
                                    uiOutput("messageStream")),
                    box(title = "Contact", id='profile', collapsible = TRUE, collapsed = TRUE,
                                    boxProfile(
                                      image = "https://api.dicebear.com/9.x/bottts/svg",
                                      title = textOutput("name"),
                                        bordered = TRUE,
                                        boxProfileItem(
                                        title = "Number of messages",
                                        description = textOutput("f")
                                          ),
                                        boxProfileItem(
                                        title = "First message",
                                        description = textOutput("firstDate")
                                          ),
                                        boxProfileItem(
                                        title = "Last message",
                                        description = textOutput("lastDate")
                                          )
                                        )
                          )
                   
                        )
          ),
          tabPanel("Search",
                   box(width = NULL, title = "Search messages (all contacts)",
                       solidHeader = TRUE, status = "warning",
                       textInput("keyword", "Keyword", placeholder = "Type a word or phrase"),
                       DT::DTOutput("searchResults")))
    )
        
        
        
        
),
#-----------Right Panel
    controlbar = dashboardControlbar(skin = "dark", controlbarMenu(
              id = "menu",
              controlbarItem( "Themes","Change Color theme",br(),hr()),
              controlbarItem( "Tab 2" )
    ) ),
    footer= dashboardFooter(left="By minesweeper106",
                            right= socialButton(href = "https://github.com/minesweeper106",icon = icon("github"))
    )
  
)
#------------------------------------
#-----------SERVER-------------------
#------------------------------------
#------------------------------------
server <- function(input, output, session) {
  
  
    db <- reactive({
        req(input$file)
        getDB(file = input$file$datapath)
    })
    whogen <- reactive({
        unique(db()$who)
    })
    observeEvent(whogen(), {
        choices <- whogen()
        updateSelectInput(session, "contact", choices = choices)
    })
    
    # Avatars (generated by DiceBear, no personal/expiring URLs)
    avatar_received <- "https://api.dicebear.com/9.x/bottts/svg?seed=contact"
    avatar_sent     <- "https://api.dicebear.com/9.x/bottts/svg?seed=me&backgroundColor=b6e3f4"

    # Messages for the selected contact (newest first)
    parsed <- reactive({
        req(input$contact)
        parser(db(), input$contact)
    })

    output$name <- renderText(input$contact)
    output$f <- renderText(nrow(parsed()))
    # parsed() is sorted newest first: first row = last message, last row = first
    output$firstDate <- renderText(tail(parsed()$xdate, 1))
    output$lastDate  <- renderText(head(parsed()$xdate, 1))

    # The whole conversation is rendered in one go (a single message to the
    # browser) instead of one updateUserMessages() call per message.
    output$messageStream <- renderUI({
        p <- parsed()
        msgs <- lapply(seq_len(nrow(p)), function(i) {
            received <- p$sent[i] == 0
            userMessage(
                author = p$who[i],
                date   = as.character(p$xdate[i]),
                image  = if (received) avatar_received else avatar_sent,
                type   = if (received) "received" else "sent",
                # attachments / empty messages have NA text
                if (is.na(p$text[i])) "" else p$text[i]
            )
        })
        userMessages(width = NULL, status = "danger", msgs)
    })

    # Keyword search across all contacts, newest first (debounced typing)
    keyword <- debounce(reactive(input$keyword), 400)
    output$searchResults <- DT::renderDT({
        res <- searchMessages(parser(db()), keyword())
        data.frame(
            Handle = res$who,
            Date   = res$xdate,
            Text   = res$text,
            `Sent/Received` = ifelse(res$sent == 1, "Sent", "Received"),
            check.names = FALSE
        )
    }, rownames = FALSE, options = list(pageLength = 25,
                                        language = list(emptyTable = "No matching messages")))

    # Expand the boxes once a contact is selected
    observeEvent(input$contact, {
        req(input$contact)
        if (isTRUE(input$messageBox$collapsed)) updateBox("messageBox", action = "toggle")
        if (isTRUE(input$profile$collapsed))    updateBox("profile",    action = "toggle")
    })
}
# Run the application
shinyApp(ui = ui, server = server)
